# Session 2: Functions and Fundamental Packages - Solutions

In [ ]:
import warnings
warnings.filterwarnings("ignore")

This is a python notebook constructed by Lennert Van der Schraelen and Prof Dr Kristof Stouthuysen.

All authors and supervisors are members of the **Centre for Financial Leaderschip and Digital Transformation** at **Vlerick Business School**.

### Introduction: CRISP-DM

CRISP-DM: Cross-Industry Standard Process for Data Mining
- Open standard process model that describes the data science life cycle
- 6 phases with no strict sequence: often moving back and forward between phases is necessary

<h3> CRISP-DM </h3>
<center> <img src="https://www.dropbox.com/s/tqusp6d2viwqv5f/CRISP-DM.PNG?raw=1" width=50%/> </center>

### Workflow of this Session

<img src="https://www.dropbox.com/s/zemag6tclhakqk3/workflow2.png?raw=1">

## 2.1 Functions

### What is a function

In Python, a function definition begins with the `def` keyword.

One can provide a list of parameters inside the round brackets `(.)`.

By using `return`, we can return a result to the function caller.

The function `add_number()` takes two numbers and adds them together.

In [ ]:
def add_number(x,y):
    sum = x + y
    return sum

add_number(2,4)

6

### Functions: A second example

It is possible to specify a default parameter value (`z=1` in the example).

When calling a function, use an argument (`2` and `4` in the example) or keyworded argument (`z = 3` in the example).

Functions make code more manageable and easier to understand.

In [ ]:
def add_numbers(x, y, z=1):
    sum = x + y + z
    return sum

print(add_numbers(2, 4))
print(add_numbers(2, 4,z=3))

7
9

<center>
<img src="https://www.dropbox.com/s/mtzp6vhsurv6id9/goose.PNG?raw=1" width="200" class="center">
<center>

### Built-in functions

Python provides a number of functions that are always available.

For example, the built-in `max()` function returns the item with the highest value.

Or the the built-in `type()` function  returns the class type (integer in the example).

In [ ]:
num_list = [1, 2, 3]
x = max(num_list)
print(x)
print(type(x))

3
<class 'int'>

#### Built-in functions: map & list

One important built-in function is the `map` function.

The `map()` function allows us to apply a given function on an iterable (you can iterate over it) and returns this iterable.

The `list()` function takes an iterable object as input and creates a new list.

This allows us to calculate the double of each element of a list.

In [ ]:
def addition(x):
    return x + x

num_list = [1, 2, 3]
result = map(addition, num_list)
print(list(result))

[2, 4, 6]

#### Lambda functions

The `lambda` keyword defines an anonymous function (=lambda function) in Python.

Lambda functions can be used for functions that only return a single value.

Lambda functions make your code more concise. The bottom code on the right calculates the double of each element of a list.

In [ ]:
# (lambda x: x + x)(2)

In [ ]:
# num_list = [1, 2, 3]
# result = map(lambda x: x + x,
#             num_list)
#print(list(result))

#### Lambda functions: a second example

A lambda function can have multiple inputs.

On the right, we calculate the sum of the elements of 2 different lists.

In [ ]:
num_list_1 = [1, 2, 3]
num_list_2 = [4, 5, 6]

result = map(lambda x, y: x + y,
         num_list_1, num_list_2)
print(list(result))

#### Functions exercise

Create a function that returns the following value

<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=default'></script> $$ x=\dfrac{v}{(1 + r)^t}. $$

The variable 't' represents the number of periods, the variable 'r' the interest rate and the variable 'v' the future sum received. The output 'x' represents the present value of an item.

In [ ]:
def p_v(v, r,t):
    x =  v / ((1+r)**t)
    return x

print(p_v(v=5,r=0.01,t=10))

4.526434773464916

In [ ]:
v = [1000, 2000, 3000]
t = [1, 2, 3]
r = [0.05, 0.05, 0.05]

x = lambda v,r,t: v / ((1+r)**t)
result = map(x, v, r, t)
list(result)

[952.3809523809523, 1814.0589569160998, 2591.512795594428]

## 2.2 Numpy

### The Numpy library

<a href="https://numpy.org/doc/stable/"> `Numpy`</a> is a fundamental package for numeric computing in Python.

By using imports, one can get access to code from modules/packages. To import a module, use the `import` statement.

Use the <a href="https://numpy.org/doc/stable/reference/generated/numpy.array.html"> `np.array()`</a> function to create an array.

In [ ]:
# import numpy as np
# num_list = [1, 2, 3]
# array = np.array(num_list)
# print(array)

In [ ]:
import numpy as np
num_list = [1, 2, 3]
array = np.array(num_list)
print(array)

[1 2 3]

### Introduction to Numpy

NumPy provides powerful ways to create, store, and/or manipulate data.

A NumPy array is a grid of items, all of the same type. In this example, the items are strings.  

If we pass in a list of lists in `np.array()`, we create a multi-dimensional array.

By calling the `shape` attribute, we can print the length of each dimension.

In [ ]:
# cloth_array =   \
#    np.array([['shirt','hat','dress'],
#    ['shirt','hat','dress']])
# print(cloth_array)
# print("The shape equals {0}"
#      .format(cloth_array.shape))

### Creating arrays

<a href="https://numpy.org/doc/stable/reference/generated/numpy.zeros.html"> `np.zeros()`</a>
returns a new array of given shape and type, filled with zeros.

<a href="https://numpy.org/doc/stable/reference/generated/numpy.ones.html"> `np.ones()`</a>
returns a new array of given shape and type, filled with ones.

<a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html"> `np.random.rand()`</a>
returns random values (between zero and one) of a given shape.

In [ ]:
print(np.zeros((2,3)))
print('\n')
print(np.ones((2,3)))
print('\n')
print(np.random.rand(2,2))

[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]]


[[0.1380025  0.68366395]
 [0.04610825 0.04153786]]

### Generating arrays


One can do statistical tests by using <a href="https://docs.scipy.org/doc/scipy/"> `Scipy`</a>.

In this example, we generate numbers from 2 normal  distributions.

For example, the two-sided test <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html"> `ttest_ind()`</a> (null hypothesis: 2 independent samples have identical average (expected) values).

In [ ]:
from scipy.stats import ttest_ind

female_length = np.random.normal(loc=168,
        scale=6,size=100000)
male_length = np.random.normal(loc=178,
        scale=6,size=100000)

res = ttest_ind(female_length,male_length)
print(res)

Ttest_indResult(statistic=-370.8980200922665, pvalue=0.0)

### Operations

Many mathematical manipulations like addition, subtraction, square, ... can be done on arrays.

To execute an element-wise multiplication, use `*` or the function <a href="https://numpy.org/doc/stable/reference/generated/numpy.multiply.html"> `np.multiply()`</a>

If one applies a comparison operator on an array, a boolean array will be returned.

In [ ]:
# a = np.array([10,20,30])
# b = np.array([1, 2, 3])
# prod_array = a*b
# print("Element wise product {0}".format(prod_array))
# print("Boolean array {0}".format(prod_array > 30))

### Operations

By calling the `T` attribute one can calculate the transpose of an array. The same can be achieved by using <a href="https://numpy.org/doc/stable/reference/generated/numpy.transpose.html"> `np.transpose()`</a>.

Besides element-wise manipulation, it is important to know that Numpy supports dot products and matrix manipulations. This can be achieved by using the `@` sign or the <a href="https://numpy.org/doc/stable/reference/generated/numpy.dot.html"> `np.dot()`</a> function.

In [ ]:
a = np.array([[10,20],[30,40]])
b = np.array([[1, 2],[3,4]])

print("Transpose of a {0}".format(a.T))
print("Element wise product {0}".format(a*b))
print("Dot product {0}".format(a@b))

### Calculations over columns and rows

How to specify the axis along which we want to compute  a numpy function (like <a href="https://numpy.org/doc/stable/reference/generated/numpy.mean.html"> `np.mean()`</a>)?

Axis 0 acts on all rows in each column.

Axis 1 acts on all columns in each row.

In [ ]:
# price_array = np.array([[9.99, 2.99, 35.99],
#    [19.99, 5.99, 55.99]])
# print("Mean over whole array {0}"
#    .format(price_array.mean()))
# print("Mean of each column {0}"
#    .format(price_array.mean(axis=0)))
# print("Mean of each row {0}"
#    .format(price_array.mean(axis=1)))

### Indexing and slicing

For data manipulation and analysis, it is very important to select data based on conditions.

To select an element of an array, provide the row and column indices in square brackets.

Notice that in python, the indices start at 0.

To select a single row, specify only one index in square brackets.

In [ ]:
cloth_arr = cloth_array.T
print(cloth_arr)
print("The first element: {0}".format(cloth_arr[0,0]))
print("The second row: {0}".format(cloth_arr[1]))

### Indexing and slicing

To select multiple rows, use a list of row indices.

Similarly, to select multiple columns, use a list of column indices.

To select multiple sequential rows, one can use slice notation (the ` : ` sign).

Similarly, to select multiple sequential columns, one can use slice notation.

In [ ]:
print(cloth_arr)
print("Second column of the first two rows {0}"
      .format(cloth_arr[0:2,1]))
print("The first two columns of the second row {0}"
      .format(cloth_arr[1,[0,1]]))

### Indexing and slicing

The `:` sign does have another handy application.

To select a whole row, use `,:` to indicate all columns within that row.

Idem, use `:,` to indicate all rows within that column.

In [ ]:
print(cloth_arr)
print("The second row: {0}".format(cloth_arr[1,:]))
print("The first column {0}".format(cloth_arr[:,0]))

#### Numpy exercise

Calculate the element wise product of the two rows in the price array.

Many solutions are possible.

In [ ]:
price_array = np.array([[9.99, 2.99, 35.99],
                        [19.99, 5.99, 55.99]])
price_array

#### Solution

In [ ]:
print(price_array[0] * price_array[1])
print(price_array[0,:] * price_array[1,:])
print(price_array[[0,1],:].prod(axis = 0))

## 2.3 Pandas

### The Pandas library

Data scientists spend most of their time preparing data (data wrangling) before modelling.

Big data applications must support mixed data types, customized indexing and missing data.

<a href="https://pandas.pydata.org/docs/">`Pandas`</a> is a python library that is often used for working with data sets.

<img src="https://www.dropbox.com/s/oz9v0cyknjcwcva/panda.jpg?raw=1" width="25%" align="right">

### Series

One of the core structures in Pandas are Series.

You can create a Series by passing in a list of values.

The first 'column' is the index, the second 'column' is your actual data.

In this example, Pandas identifies the type of data in this Series as "object".

In [ ]:
# products = ['Shirt', 'Hat', 'Dress']
# prod_series

import pandas as pd
products = ['Shirt', 'Hat', 'Dress']
prod_series = pd.Series(products)
prod_series

0    Shirt
1      Hat
2    Dress
dtype: object

In [ ]:

import pandas as pd

products = ['Shirt', 'Hat', 'Dress']
prod_series = pd.Series(products)
prod_series

0    Shirt
1      Hat
2    Dress
dtype: object

### Series

A Series can also be created directly from dictionary data.

We can get the indices by using the `index` attribute.

In [ ]:
cloth_dict = {'Shirt': [9.99],
              'Hat': [2.99],
              'Dress': [35.99]}
series_cloth = pd.Series(cloth_dict)
print(series_cloth)
print(series_cloth.index)

Shirt     [9.99]
Hat       [2.99]
Dress    [35.99]
dtype: object
Index(['Shirt', 'Hat', 'Dress'], dtype='object')

### DataFrames

A  DataFrame is two-dimensional, size-mutable and potentially heterogeneous tabular data.

You can rename column names with the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html">`df.rename()`</a> method.

Each column in a DataFrames is a Series.

In [ ]:
cloth_dict = {'Shirt': [9.99, 19.99],
             'Hat': [2.99, 5.99],
             'Dress': [35.99, 55.99]}
df_cloth = pd.DataFrame(cloth_dict)
df_cloth.index = ['Cheap', 'Expensive']
df_cloth

           Shirt   Hat  Dress
Cheap       9.99  2.99  35.99
Expensive  19.99  5.99  55.99

In [ ]:
cloth_dict = {'Shirt': [9.99, 19.99],
              'Hat': [2.99, 5.99],
              'Dress': [35.99, 55.99]}
df_cloth = pd.DataFrame(cloth_dict)
df_cloth.index = ['Cheap','Expensive']
df_cloth

           Shirt   Hat  Dress
Cheap       9.99  2.99  35.99
Expensive  19.99  5.99  55.99

### Selecting subsets

To select a column, provide the column name in brackets.

In [ ]:
print("The price of a dress:\n{0}"
    .format(df_cloth['Dress']))

The price of a dress:
Cheap        35.99
Expensive    55.99
Name: Dress, dtype: float64

### Selecting subsets

One can easily select various subsets by label using the `loc` command.

In [ ]:
# The price of a dress
# The price of cheap clothes

print(df_cloth.loc[:,'Dress'])
print('\n')
print(df_cloth.loc['Cheap',:])

Cheap        35.99
Expensive    55.99
Name: Dress, dtype: float64


Shirt     9.99
Hat       2.99
Dress    35.99
Name: Cheap, dtype: float64

In [ ]:
print("The price of a dress:\n{0}"
.format(df_cloth.loc[:,'Dress']))
print("The price of cheap clothes:\n{0}"
.format(df_cloth.loc['Cheap',:]))

The price of a dress:
Cheap        35.99
Expensive    55.99
Name: Dress, dtype: float64
The price of cheap clothes:
Shirt     9.99
Hat       2.99
Dress    35.99
Name: Cheap, dtype: float64

### Selecting subsets


You can also easily select various subsets by index using the `iloc` command.

To select multiple sequential rows/columns, you can again use the slice notation or a list of indices.

In [ ]:
# The price of a hat and a dress

print(df_cloth.iloc[:,[1,2]])
print(df_cloth.iloc[:,1:3])

            Hat  Dress
Cheap      2.99  35.99
Expensive  5.99  55.99
            Hat  Dress
Cheap      2.99  35.99
Expensive  5.99  55.99

In [ ]:
print("Hat & Dress:\n{0}"
.format(df_cloth.iloc[:,1:3]))
print("Hat & Dress:\n{0}"
.format(df_cloth.iloc[:,[1,2]]))

Hat & Dress:
            Hat  Dress
Cheap      2.99  35.99
Expensive  5.99  55.99
Hat & Dress:
            Hat  Dress
Cheap      2.99  35.99
Expensive  5.99  55.99

### Conditionally extract

It is possible to extract certain subsets of a DataFrame based on certain conditions.

In [ ]:
# Products (Cheap above 20) (incl_in_stud_notebook)

boole = df_cloth.loc['Cheap',:] > 20
boole
df_exclus =df_cloth.loc[:,boole]
df_exclus

           Dress
Cheap      35.99
Expensive  55.99

In [ ]:
df_exclus = df_cloth.loc[:,
df_cloth.loc['Cheap',:] > 20]
print(df_cloth)
print(df_exclus)

           Shirt   Hat  Dress
Cheap       9.99  2.99  35.99
Expensive  19.99  5.99  55.99
           Dress
Cheap      35.99
Expensive  55.99

### Condition and replace

It is possible to replace certain subsets of a DataFrame based on certain conditions.

In [ ]:
print(df_cloth)
df_cloth.loc['Expensive',
             'Hat'] = 8.99
print(df_cloth)

           Shirt   Hat  Dress
Cheap       9.99  2.99  35.99
Expensive  19.99  5.99  55.99
           Shirt   Hat  Dress
Cheap       9.99  2.99  35.99
Expensive  19.99  8.99  55.99

### Calculations on groups

Pandas is able to select data based on groups and understand aggregated data on a group level.

The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html">`df.groupby()`</a>
method is able group large amounts of data and compute operations on these groups.

In the example, we made a DataFrame with multiple rows that contain expensive prices.

In [ ]:
cloth_ex = \
    {'Price_Range':
   ['Cheap','Expensive','Expensive'],
     'Shirt': [9.99, 19.99, 25.99],
     'Hat': [2.99, 5.99, 15.99],
     'Dress': [35.99, 55.99, 79.99]}
df_cloth_ex = pd.DataFrame(cloth_ex)
df_cloth_ex

  Price_Range  Shirt    Hat  Dress
0       Cheap   9.99   2.99  35.99
1   Expensive  19.99   5.99  55.99
2   Expensive  25.99  15.99  79.99

### Calculations on groups

We are able to split the data into groups based on the values in the Price_Range.

The `groups` attribute is a dictionary whose keys are the computed unique groups.

A single group can be selected using the `get_group()` method.

In [ ]:
# Group by 'Price_Range'
# grouped

grouped = df_cloth_ex.groupby('Price_Range')
grouped

print(grouped.groups)
print(grouped.get_group('Expensive'))

{'Cheap': [0], 'Expensive': [1, 2]}
  Price_Range  Shirt    Hat  Dress
1   Expensive  19.99   5.99  55.99
2   Expensive  25.99  15.99  79.99

In [ ]:
grouped = df_cloth_ex.    \
     groupby('Price_Range')

print(grouped.groups)
print('\n')
print(grouped.get_group("Cheap"))

{'Cheap': [0], 'Expensive': [1, 2]}


  Price_Range  Shirt   Hat  Dress
0       Cheap   9.99  2.99  35.99

### Calculations on groups

Various Pandas methods can be called to perform computations on the grouped data. This is called 'aggregation'.

On the right side, we first compute the size of each group.

Next, we also calculate the sum of the prices of each group.

In [ ]:
print(df_cloth_ex)
print(df_cloth_ex.groupby('Price_Range').size())
print(df_cloth_ex.groupby('Price_Range').sum())

  Price_Range  Shirt    Hat  Dress
0       Cheap   9.99   2.99  35.99
1   Expensive  19.99   5.99  55.99
2   Expensive  25.99  15.99  79.99
Price_Range
Cheap        1
Expensive    2
dtype: int64
             Shirt    Hat   Dress
Price_Range
Cheap         9.99   2.99   35.99
Expensive    45.98  21.98  135.98

### Combining DataFrames

The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html">`pd.merge()`</a> function allows you to combine two DataFrames horizontally.

This functions aligns a DataFrame's column or index with another DataFrame's column or index.

There are different types of merges that can be performed, we discuss `left`, `right`, `outer` and `inner`.

<center>
<img src="https://www.dropbox.com/s/30fsjuccz3r438h/venn.png?raw=1" width="500">
<center>

### Combining DataFrames

In [ ]:
cloth_1 = pd.DataFrame([{'Name':'Hat','Range':'Cheap'},
                        {'Name':'Shirt','Range':'Expensive'}]).set_index('Name')
cloth_2 = pd.DataFrame([{'Name':'Hat','Range':'Expensive'},
                        {'Name':'Dress','Range':'Expensive'}]).set_index('Name')
print(cloth_1)
print("\n")
print(cloth_2)

           Range
Name
Hat        Cheap
Shirt  Expensive


           Range
Name
Hat    Expensive
Dress  Expensive

### Combining DataFrames

In [ ]:
print(pd.merge(cloth_1, cloth_2,
        how='left', on='Name'))
print("\n")
print(pd.merge(cloth_1, cloth_2,
        how='right', on='Name'))

         Range_x    Range_y
Name
Hat        Cheap  Expensive
Shirt  Expensive        NaN


      Range_x    Range_y
Name
Hat     Cheap  Expensive
Dress     NaN  Expensive

In [ ]:
print(pd.merge(cloth_1, cloth_2,
        how='inner', on='Name'))
print("\n")
print(pd.merge(cloth_1, cloth_2,
        how='outer', on='Name'))

     Range_x    Range_y
Name
Hat    Cheap  Expensive


         Range_x    Range_y
Name
Hat        Cheap  Expensive
Shirt  Expensive        NaN
Dress        NaN  Expensive

### Combining DataFrames

The function <a href="https://pandas.pydata.org/docs/reference/api/pandas.concat.html">`pd.concat()`</a> allows you to simply concatenate Pandas objects along a particular axis.

Remember `axis = 0` acts in each column along the rows and `axis = 1` acts in each row along the columns.

In [ ]:
print(pd.concat([cloth_1, cloth_2],
        axis=0))
print("\n")
print(pd.concat([cloth_1, cloth_2],
        axis=1))

           Range
Name
Hat        Cheap
Shirt  Expensive
Hat    Expensive
Dress  Expensive


           Range      Range
Name
Hat        Cheap  Expensive
Shirt  Expensive        NaN
Dress        NaN  Expensive

### Importing and exporting data

 A comma-separated values (`.csv`) file uses a comma to separate data values.

The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html">`df.to_csv()`</a> method allows you to write a csv file.

The <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html">`pd.read_csv()`</a> function allows you to read a csv file.

In [ ]:
# Write csv file to directory
df_cloth.to_csv('df_cloth.csv',index=True)


# Read csv file from directory
df_read = pd.read_csv('df_cloth.csv',index_col=0)

print(df_read)

           Shirt   Hat  Dress
Cheap       9.99  2.99  35.99
Expensive  19.99  8.99  55.99
           Shirt   Hat  Dress
Cheap       9.99  2.99  35.99
Expensive  19.99  8.99  55.99

### Additional methods

Use the <a href="https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.DataFrame.T.html">`df.T` </a> attribute to calculate the transpose.

Use the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html">`df.drop()`</a> method to drop certain row or columns.

Use the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html">`df.describe()`</a> method to calculate basic descriptive statistics.

Use the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html">`df.sort_values()`</a> method to sort by the values along either axis.

In [ ]:
df_cloth

           Shirt   Hat  Dress
Cheap       9.99  2.99  35.99
Expensive  19.99  8.99  55.99

In [ ]:
df_cloth.describe()

           Shirt       Hat      Dress
count   2.000000  2.000000   2.000000
mean   14.990000  5.990000  45.990000
std     7.071068  4.242641  14.142136
min     9.990000  2.990000  35.990000
25%    12.490000  4.490000  40.990000
50%    14.990000  5.990000  45.990000
75%    17.490000  7.490000  50.990000
max    19.990000  8.990000  55.990000

#### Pandas exercise

Try to extract the prices of a shirt and sort them from high to low.

Many solutions are possible.

In [ ]:
df_cloth

           Shirt   Hat  Dress
Cheap       9.99  2.99  35.99
Expensive  19.99  8.99  55.99

In [ ]:
df_cloth.loc[:, 'Shirt'].sort_values(ascending = False)

Expensive    19.99
Cheap         9.99
Name: Shirt, dtype: float64

#### Solution

In [ ]:
print((df_cloth.iloc[:,0]).sort_values(ascending=False))
print(df_cloth.loc[:,'Shirt'].sort_values(ascending=False))

Expensive    19.99
Cheap         9.99
Name: Shirt, dtype: float64
Expensive    19.99
Cheap         9.99
Name: Shirt, dtype: float64

## 2.4 Additional Exercises - Solutions

### Exercise 1

Create a list called <font face="Courier New">cube</font> that contains only the **cubes of the odd numbers** from the following list:

<font face="Courier New">numbers = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6]</font>

In [ ]:
cube = []
numbers = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6]
for x in numbers:
    if x % 2 != 0:   # the remainder when dividing by 2 is not zero --> odd number
        cube.append(x**3)
cube

[27, 343, 1, 729, 125]

In [ ]:
# Other way
cube = [x**3 for x in numbers if x % 2 != 0]
cube

[27, 343, 1, 729, 125]

### Exercise 2

Melissa's world trip was cancelled due to COVID-19 pandemic. As a result, she receives a refund of €10,000. She decides to invest the money in a savings account that yields 5% interest per annum, compounded yearly. <br>
a) Melissa leaves all the interest in the account. **Calculate and display the amount of money in the account at the end of each year for 10 years, assuming no withdrawals.** <br>
b) Melissa decides that once the total balance (principal plus interest) in the account reaches €14,000 or more, she will withdraw all the accumulated interest, leaving only the original €10,000 principal in the account.
**Display the exact amount of money that Melissa withdraws when the balance goes over the €14,000 and recalculate the amount of money in the account again until the end of year 10.** <br>

Tip: Use the compound interest formula for calculating the amount of money in the account after n years: <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=default'></script> $$ {p(1 + r)^n} $$

where <br>
<i>p</i> is the original amount invested (i.e., the principal) <br>
<i>r</i> is the annual interest rate <br>
<i>n</i> is the number of years

In [ ]:
# Exercise 2 a)
amount = 0
principal = 10000
rate = 0.05
for year in range(1, 11):
    amount = principal * (1 + rate) ** year
    print(f'{year:2}{amount:10.2f}')

 1  10500.00
 2  11025.00
 3  11576.25
 4  12155.06
 5  12762.82
 6  13400.96
 7  14071.00
 8  14774.55
 9  15513.28
10  16288.95

In [ ]:
# Exercise 2 b)
principal = 10000
threshold = 14000
rate = 0.05
withdrawal = 0
for year in range(1, 11):
    if (year == 1):
        amount = principal
    amount = amount*(1+rate)
    print(f"Amount at the end of year {year:12} is {amount:10.2f}")
    if amount >= threshold:
        withdrawal = amount-principal
        amount = principal
        print(f"Amount withdrawn at the end of year {year:2} is {withdrawal:10.2f}")

Amount at the end of year            1 is   10500.00
Amount at the end of year            2 is   11025.00
Amount at the end of year            3 is   11576.25
Amount at the end of year            4 is   12155.06
Amount at the end of year            5 is   12762.82
Amount at the end of year            6 is   13400.96
Amount at the end of year            7 is   14071.00
Amount withdrawn at the end of year  7 is    4071.00
Amount at the end of year            8 is   10500.00
Amount at the end of year            9 is   11025.00
Amount at the end of year           10 is   11576.25

### Exercise 3

The local clothing store had a busy day of sales, and now it’s time to see which items brought in the most profit! The store sells a variety of products, including shoes, T-shirts, suits, and sweatshirts. We’ve gathered the data from one day of sales and now need your help to find out **which products made a profit** (calculated as price - cost) **greater than €15.** <br>
Once you find them, export these top-selling items into a CSV file to share with the store manager. The Id represents the transaction ID.

Methods that could be useful:

<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html">`df.drop()`</a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html">`df.groupby()`</a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html">`df.to_csv()`</a>

In [ ]:
import pandas as pd
sales_id = pd.DataFrame({
'Id': [456,324,753,124,459,794],
'Product':['Shoes', 'Shoes', 'Suit','T-Shirt', 'Sweatshirt','T-Shirt'],
'Price':[40,60,10,100,25, 15],
'Cost':[20, 35,5, 85, 20, 10]})
sales_id

    Id     Product  Price  Cost
0  456       Shoes     40    20
1  324       Shoes     60    35
2  753        Suit     10     5
3  124     T-Shirt    100    85
4  459  Sweatshirt     25    20
5  794     T-Shirt     15    10

Modify the DataFrame by creating a 'Profit' column.

In [ ]:
sales_id['Profit'] = sales_id['Price']- sales_id['Cost']

sales_id

    Id     Product  Price  Cost  Profit
0  456       Shoes     40    20      20
1  324       Shoes     60    35      25
2  753        Suit     10     5       5
3  124     T-Shirt    100    85      15
4  459  Sweatshirt     25    20       5
5  794     T-Shirt     15    10       5

Drop the 'Id' column.

In [ ]:
sales = sales_id.drop('Id', axis = 1)
sales

      Product  Price  Cost  Profit
0       Shoes     40    20      20
1       Shoes     60    35      25
2        Suit     10     5       5
3     T-Shirt    100    85      15
4  Sweatshirt     25    20       5
5     T-Shirt     15    10       5

Use the groupby() method to group the data and compute operations on these groups.

In [ ]:
grouped_sales = sales.groupby(['Product']).sum()
grouped_sales

            Price  Cost  Profit
Product
Shoes         100    55      45
Suit           10     5       5
Sweatshirt     25    20       5
T-Shirt       115    95      20

Extract the products that have a total profit greater than €15.

In [ ]:
boolean = grouped_sales['Profit']>15
boolean

Product
Shoes          True
Suit          False
Sweatshirt    False
T-Shirt        True
Name: Profit, dtype: bool

The following products have a total profit greater than €15. Export them to csv.

In [ ]:
prof_prod = pd.Series(grouped_sales[boolean].index)
prof_prod.to_csv('prof_prod.csv')

print(prof_prod)

0      Shoes
1    T-Shirt
Name: Product, dtype: object

### Exercise 4

The store manager is also particularly interested in finding out who their top-spending customer is! Fortunately, there is a new file  'transaction_client_id.csv' that contains transaction IDs along with the names of the clients who made the purchases.


Read this csv file using pandas and deduce **which person buys on average the most expensive products.** For this, you will **also need the dataframe from exercise 3** and **combine them**.

Functions that could be useful:

<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html">`pd.read_csv()`</a>,<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html">`pd.merge()`</a>

In [ ]:
%%capture

!wget https://drive.google.com/uc?id=1w5erPwe0FK9CSZ0V_pxFXaw57z1SEVUx -O transaction_client_id.csv

trans_cl_id = pd.read_csv('transaction_client_id.csv', delimiter=",")

In [ ]:
print(trans_cl_id)

    Id   Name
0  324   Mary
1  124   John
2  794  Sarah
3  456  Sarah
4  459  Susan
5  753   John

Merge the DataFrames 'trans_cl_id' and 'sales_id' based on the values in column "Id".

In [ ]:
#Id is a common column in 2 DataFrames
merged_df_id = pd.merge(trans_cl_id, sales_id, how = 'inner', on ='Id')
merged_sales_df = merged_df_id.drop('Id', axis=1)
merged_sales_df

    Name     Product  Price  Cost  Profit
0   Mary       Shoes     60    35      25
1   John     T-Shirt    100    85      15
2  Sarah     T-Shirt     15    10       5
3  Sarah       Shoes     40    20      20
4  Susan  Sweatshirt     25    20       5
5   John        Suit     10     5       5

Use the groupby() method to group the data and compute operations on these groups.

In [ ]:
merged_grouped = merged_sales_df[['Price', 'Name']].groupby(['Name']).mean()
merged_grouped

       Price
Name
John    55.0
Mary    60.0
Sarah   27.5
Susan   25.0

In [ ]:
name = merged_grouped.idxmax()['Price']  # returns the index of the maximum value for the Price column
merged_grouped['Price'].index
print("{0} buys on average the most expensive products"
      .format(name))

Mary buys on average the most expensive products